version: "3.3"
services:
  myapp:
    image: app:v1
    container_name: myapp
    #command: sh -c "/app/Time_go-zero_csdn/run_rpc.sh && sleep 10 && /app/Time_go-zero_csdn/run_api.sh"
    command:
      - /bin/sh
      - -c
      - |
          /app/Time_go-zero_csdn/csdn/user/cmd/rpc/user_rpc -f /app/Time_go-zero_csdn/csdn/user/cmd/rpc/etc/user.yaml&
          /app/Time_go-zero_csdn/csdn/channel/cmd/rpc/article_rpc -f /app/Time_go-zero_csdn/csdn/channel/cmd/rpc/etc/channel.yaml&
          sleep 10
          /app/Time_go-zero_csdn/csdn/user/cmd/api/user_api -f /app/Time_go-zero_csdn/csdn/user/cmd/api/etc/api-api.yaml&
          /app/Time_go-zero_csdn/csdn/channel/cmd/api/article_api -f /app/Time_go-zero_csdn/csdn/channel/cmd/api/etc/api-api.yaml
    ports:
      - "8079:8079"
      - "8888:8888"
      - "8081:8081"
      - "8889:8889"
    restart: unless-stopped
    privileged: true
