version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - csdn_net

  kibana:
    image: kibana:7.6.1
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - csdn_net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  go-stash:
    image: kevinwan/go-stash:1.0
    container_name: go-stash
    environment:
      TZ: Asia/Shanghai
    user: root
    restart: always
    volumes:
      - /data/go-stash/etc:/app/etc
    networks:
      - csdn_net
    depends_on:
      - elasticsearch
      - kafka

  filebeat:
    image: elastic/filebeat:7.6.1
    container_name: filebeat
    environment:
      TZ: Asia/Shanghai
    user: root
    restart: always
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - /data/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - csdn_net
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 2181:2181
    networks:
      - csdn_net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - csdn_net
    depends_on:
      - zookeeper
networks:
  csdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
