// Code generated by goctl. DO NOT EDIT.
package types

type CityInfo struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Pid  int64  `json:"pid"`
}

type CityPid struct {
	Pid []CityInfo `json:"pid"`
}

type ChinaMapRequest struct {
}

type ChinaMapResponse struct {
	Province CityPid `json:"province"`
	City     CityPid `json:"city"`
	District CityPid `json:"district"`
}

type CityRequest struct {
	Pid int64 `json:"pid,optional"`
}

type CityResponse struct {
	City []CityInfo `json:"city"`
}
