// Code generated by goctl. DO NOT EDIT.
package types

type UserPasswordLoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type UserPasswordLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type PhoneLoginRequest struct {
	Phone string `json:"mobile"`
	Code  string `json:"sms_code"`
}

type PhoneLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type SendSmsCodeRequest struct {
}

type SendSmsCodeReponse struct {
}

type UserCurrInfoRequest struct {
}

type IsFocusUserRequest struct {
	TargetUserId int64 `json:"target_user_id,optional"`
}

type IsFocusUserResponse struct {
	IsFocusUser bool `json:"isFocusUser"`
}

type UserCurrInfoResponse struct {
	UserName  string `json:"user_name"`
	HeadPhoto string `json:"head_photo"`
	Introduce string `json:"introduce"`
	CodeYear  int32  `json:"code_year"`
	Career    string `json:"career"`
	Focus     int32  `json:"focus"`
	Fans      int32  `json:"fans"`
	Visitor   int32  `json:"visitor"`
}
