version: '3'
services:
  myapp:
    image: app:v5
    container_name: my_csdn
    command: bash -c "cd /csdn && ./modd"
    restart: unless-stopped
    privileged: true
    ports:
      - "0.0.0.0:8888:8888"  #user
    #  - "0.0.0.0:8893:8893"  #order
      - "0.0.0.0:8889:8889"  #article
      - "0.0.0.0:8890:8890"  #im
      - "0.0.0.0:8891:8891"  #product
      - "0.0.0.0:8895:8895"  #city
    volumes:
      - /root/go/src/Time_go-zero_csdn:/csdn
    networks:
      - csdn_net
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
        - csdn_net  
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - csdn_net
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    networks:
      - csdn_net
networks:
  csdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.100.0/24
