// Code generated by goctl. DO NOT EDIT.
package types

type Sku struct {
	SkuId  int64  `json:"sku_id"`
	SpecId string `json:"spec_id"`
	Specs  string `json:"specs"`
}

type OrderCreateRequest struct {
	AddressId  int64   `json:"address_id"`
	UserId     string  `json:"user_id"`
	TotalCount int64   `json:"total_count"`
	TotalPrice float32 `json:"total_price"`
	Freight    float32 `json:"freight"`
	Version    int64   `json:"version"`
	Sn         string  `json:"sn"`
	Sku        []Sku   `json:"sku"`
}

type OrderCreateResponse struct {
	Sn string `json:"sn"`
}
