// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/internal/logic"
	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/internal/svc"
	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserPasswordLogin(ctx context.Context, in *user.UserPasswordRequest) (*user.UserPasswordResponse, error) {
	l := logic.NewUserPasswordLoginLogic(ctx, s.svcCtx)
	return l.UserPasswordLogin(in)
}
