// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/internal/logic"
	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/internal/svc"
	"liujun/Time_go-zero_csdn/csdn/user/cmd/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserLogin(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

func (s *UserServer) GenerateToken(ctx context.Context, in *user.GenerateTokenRequest) (*user.GenerateTokenResponse, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}
