Name: product.rpc
ListenOn: 0.0.0.0:8085
Etcd:
  Hosts:
  - 172.20.16.20:12379
  Key: product.rpc

DB:
  DataSource: root:liujun@tcp(172.20.16.20:13306)/csdn?charset=utf8mb4&parseTime=True&loc=Local

Redis:
  Host: 172.20.16.20:16379
  Pass: liujun
  Type: node

Cache:
  - Host: 172.20.16.20:16379
    Pass: liujun
JwtAuth:
  AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
  AccessExpire: 31536000

Log:
  ServiceName: product-rpc
  Level: info

Prometheus:
  Host: 0.0.0.0
  Port: 4003
  Path: /metrics
