// Code generated by goctl. DO NOT EDIT.
package types

type ProductSpuList struct {
	Name         string `json:"name"`
	DefaultImage string `json:"default_image"`
	Sales        int64  `json:"sales"`
	Cfavs        int64  `json:"cfavs"`
	SpuId        int64  `json:"spu_id"`
}

type SubCategory struct {
	Name string `json:"name"`
	Id   int64  `json:"id"`
}

type CategoryList struct {
	Name         string        `json:"name"`
	Id           int64         `json:"id"`
	SubCategorys []SubCategory `json:"subcategory"`
}

type ProductSpuListRequest struct {
	CategoryId int64 `json:"category_id"`
}

type ProductSpuListResponse struct {
	ProductSpus []ProductSpuList `json:"product_spus"`
}

type ProductCategoryRequest struct {
}

type ProductCategoryResponse struct {
	Categorys []CategoryList `json:"categorys"`
}
