// Code generated by goctl. DO NOT EDIT.
package types

type ProductList struct {
	Title     string `json:"title"`
	Image     string `json:"image"`
	Introduce string `json:"introduce"`
}

type SubCategory struct {
	Name string `json:"name"`
	Id   int64  `json:"id"`
}

type CategoryList struct {
	Name         string        `json:"name"`
	Id           int64         `json:"id"`
	SubCategorys []SubCategory `json:"subcategory"`
}

type ProductListRequest struct {
}

type ProductListResponse struct {
	Products []ProductList `json:"products"`
}

type ProductCategoryRequest struct {
}

type ProductCategoryResponse struct {
	Categorys []CategoryList `json:"categorys"`
}
