// Code generated by goctl. DO NOT EDIT.
// Source: im.proto

package server

import (
	"context"

	"liujun/Time_go-zero_csdn/csdn/im/cmd/rpc/internal/logic"
	"liujun/Time_go-zero_csdn/csdn/im/cmd/rpc/internal/svc"
	"liujun/Time_go-zero_csdn/csdn/im/cmd/rpc/types/im"
)

type ImServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedImServer
}

func NewImServer(svcCtx *svc.ServiceContext) *ImServer {
	return &ImServer{
		svcCtx: svcCtx,
	}
}

func (s *ImServer) UserMessageList(ctx context.Context, in *im.UserMessageListRequest) (*im.UserMessageListResponse, error) {
	l := logic.NewUserMessageListLogic(ctx, s.svcCtx)
	return l.UserMessageList(in)
}
